<!DOCTYPE php>
<php lang='en'>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="title" content="ANZAC Douglas Raymond Baker" />
    <meta itemprop="name" content="ANZAC Douglas Raymond Baker" />
    <meta property="og:title" content="ANZAC Douglas Raymond Baker" />
    <meta name="description" content="This site records the letters home during WW1 from ANZAC Douglas Raymond Baker, from September 1914 after he joined up in Gympie, Queensland, Australia to May 1918." />
    <meta itemprop="description" content="This site records the letters home during WW1 from ANZAC Douglas Raymond Baker, from September 1914 after he joined up in Gympie, Queensland, Australia to May 1918." />
    <meta id="meta-tag-description" property="og:description" content="This site records the letters home during WW1 from ANZAC Douglas Raymond Baker, from September 1914 after he joined up in Gympie, Queensland, Australia to May 1918." />

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lovers+Quarrel&family=Stalemate&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=BioRhyme&family=Libre+Baskerville&family=Libre+Franklin&family=Roboto&display=swap" rel="stylesheet">

    <title>ANZAC Douglas Raymond Baker</title>

    <!-- Keep wireframe.css for debugging, add your css to style.css -->
    <link id='wireframecss' type="text/css" rel="stylesheet" href="../wireframe.css" disabled>
    <link id='stylecss' type="text/css" rel="stylesheet" href="style.css?t=<?= filemtime("style.css"); ?>">
    <script src='../wireframe.js'></script>
  </head>

  <body>

  <header>
      <div class="tooltip"><img src='../../media/avatar.jpg' alt="D.R. Baker F.Co one of the soldiers photographed in The Queenslander Pictorial supplement to The Queenslander 1914"><span class="tooltip_text"><p>(Photograph courtesy of : John Oxley Library, State Library of Queensland [Image number: 702692-19141024-s0023-0027])</p></span></div>
      <p>ANZAC <span>Douglas Raymond</span> Baker<br><span>Letters Home</span></p>
      
      
    </header>
    <span class="poppy"></span>
    <label for="show_hide_nav"><span id="menu"></span></label>
    <input type="checkbox" name="show_hide_nav" id="show_hide_nav">
    
    <nav>

      <a href='index.php'>Home</a>
      <a href='intro.php'>Introduction</a>
      <a href='places.php'>Places</a>
      <a href='contact.php'>contact</a>
      <a href='letters.php'>Letters & Post Cards</a>
      <a href='descriptions.php'>Descriptions of Battle Action</a>
      <a href='links.php'>Links to related Materials</a>

    </nav>



    <main>
      <article class="postcards">
        <h2>Letters & Postcards</h2>
        <h3>1914</h3>
        <label for="nov_22_1914_check">November 22nd, 1914</label>
        <input type="checkbox" name="nov_22_1914_check" id="nov_22_1914_check">
        <section>
          <h3>Troopship “Omrah”. In Arabian Sea</h3>
          <p class="right_align">November 22nd. 1914.</p>
          <p>Pens are being driven at top speed in all directions for we have received word that letters will not be censored, so everyone is writing to catch the mail that is to be put ashore at Aden tomorrow or Tuesday</p>
          <p>I have kept a few notes since leaving Albany so will start from that part of our voyage and tell you all the news. I have kept a few notes since leaving Albany so will start from that part of our voyage and tell you all the news.</p>
          <p>On October 31st we moved into the wharf at Albany from the bay to get water and provisions. We passed a large cruiser [The Minatour] and she looked bosker. The H.M.A.S. Melbourne was also near. The troopship “Pera” was drawn up on the opposite side of the wharf to us and seemed to be manned chiefly by Lascars who seemed a dirty crowd. At 2.30 p.m. we were taken ashore for a march to stretch our legs. It was a grand outing and we went in fatigue dress, without rifles, around the hills of Albany and returned to the Omrah much refreshed. This was our second trip ashore. We left the Albany wharf just as the sun was setting and the town looked very pretty with the fine stretch of water in front and great green hills behind, with huge boulders sticking out here and there. The sunset was really beautiful; altogether our last view of Albany was all that could be desired. When passing the cruisers we were all lined up on deck to salute them and they dipped their flag in return. We anchored in the bay for a night.</p>
          <p>At 6.30 a.m. the first of the fleet was on the move and by 10 a.m. all the troopships were out and another stage of the journey commenced. It was a great sight and one to be long remembered, to see the boats steaming out one after the other in a long line and as they got into the open each took up its allotted position. We sailed in three lines, the Omrah being near the rear on the right flank. There were 38 troopships left Albany including ten from New Zealand. Some of the boats are very slow travellers and we had to go slow too, about 10 miles an hour. On Tuesday, after leaving Albany, sports were held on board but the weather interfered with them, being rainy and windy, besides, they were badly organized. There is a sing-song being held on deck under the leadership of the Y.M.C.A. so as I want a smoke I will proceed to go on deck and kill two birds with one stone.</p>
          <p>Later:- The sing-song is a frost so I have come to the opposite side of the saloon-deck to resume this letter. Some of the events of the sports were:- obstacle race, potato race, single stick fighting, step dance, laughing competition, best dressed clown and many others.</p>
          <p>On Friday, Nov. 6th, the “Osterley” passed us on her way to England, she was only a few hundred yards away from us and the passengers were lined up waving and cheering. It would be a great sight for them to see such a large fleet of ships so close together in mid-ocean and guarded by cruisers. That night a concert was held on board and was very good. The orchestra consisted of piano, violin, cornet and clarinet. Colonel Merrington sang “The Deathless Army”, the Y.M.C.A. chap sang “Long Live the King”. One chap gave an Australian war-cry, which nearly brought down the house. There were many other songs and recitations.</p>
          <p>Did I tell you that a whole Company [120 men][ had been transferred from the Melbourne Troopship “Hoiorata” to the Omrah at Albany. They were overcrowded on their own boat. On Saturday, Nov. 7th we were considered to be in the danger zone, being just about opposite - - - - - in the Indian Ocean. At night the ships closed up and showed as little light as possible. About this time the weather was beginning to get rather warm during the day, but we had cool breezes at night. The sunsets are glorious, different every day. We get war news by wireless and are kept up to date in that line but I can tell you, I would rather be getting wireless messages from home.</p>
          <p>We have a large canvas bath rigged up on the well deck, about 10 feet by 12 feet by 3 feet deep. (roughly 3 metres by 4 metres by 1 metre). It is filled with sea water and the chaps have a good time in it. The F Company lads went off their heads one day and started throwing each other in with their clothes. The fun waxed fast and furious but things got too hot and the officers stopped them. I just managed to escape.</p>
          <p>The following is the news of Monday 9th November.:- Going at the same pace (about 10 knots). This morning we notice a large cruiser [Japanese] (the Japs were our allies in WW1 although I don’t know that they did much) tearing across our front and learned that something was wrong on the left flank. A little later we heard by wireless that the H.M.A.S. Sydney had had an engagement with the “Emden” (a German battleship) at Cocos Island. The excitement on board was great and we eagerly awaited further news. We are nearing the Equator line and the weather is very hot. We sleep on deck at night, it is unbearable below.</p>
          <p>Nov. 10th :- Slept on the poop deck last night but was disturbed by a storm. The latest news of the fight that we got by wireless is that those in charge of the wireless station at Cocos Island noticed a strange warship and sent out S.O.S. messages which were received by the “Sydney” and 20 minutes after she [the Sydney] was within range. The strange vessel proved to be the “Emden”. The “Sydney” opened fire and blew off the funnels and ripped up the main deck of the “Emden”, only receiving slight damage herself by the latter’s fire. The Captain of the “Emden” beached his boat to save it from sinking and the “Sydney” then chased and captured a German collier, took off the crew and sunk her. The “Sydney” returned to the “Emden” which surrended. Before that the “Emden” had damaged the wireless station and cut one of the cables. Those on the Island got great credit for sticking to their posts. The “Sydney” is taking the prisoners to Colombo.</p>
          <p>Friday, Nov. 13th. Today at 8 a.m. we crossed the line but the event was celebrated yesterday afternoon when Father Neptune and his staff performed his duty well. Everyone within reach was grabbed, lathered with whitewash and shaved with a piece of tin, then thrown in the canvas bath. Some of the chaps showed fight but it was no use, they had to get their ducking. At the end Father Neptune himself was thrown into the bath and all his assistants. During the last few days a competition has been held to see which Company was the best at rifle exercises and F Company won 1st and 2nd prizes in the whole Battalion. Each Company had four squads in. This morning the New Zealand boats left us so as to get to Colombo to coal up. Beastly weather, plenty of rain and not a dry spot on deck.</p>
          <p>Monday, Nov. 16th. We are anchored outside Colombo, about half a mile from the shore. It seems to be a pretty place with many large buildings about. Long before we stopped we passed numbers of catamarans and the natives were very clever in managing these strange looking boats. Our fleet is all here and the boats are very close together. We are now allowed to have lights on deck, which is a pleasure after having to get about in the dark at night. Just received news of the death of Lord Roberts. Great excitement caused when we heard that a number of German prisoners were to be brought on board the “Omrah” to be taken to England, some of those the Sydney had taken off the Emden. They arrived about 4.30 p.m., 44 of them including 2 officers, in a motor boat from the Sydney which is in the harbour here. Try and fancy you were here and see a thousand soldiers thronging the side of the “Omrah” trying to get a look at the prisoners as they were coming on board. These Germans were received by a guard with fixed bayonets and lined up on the main deck. Their two officers were taken in and given refreshments while the men were conducted to their new quarters. A permanent guard has been formed of old soldiers to look after them, I had a good view of the proceedings. When the business was finished the anchor was raised and we moved in slowly towards Colombo. As we passed within stones throw of ship after ship the cheering from each was deafening and we answered it with a will. We passed through the gateway of the breakwater just as it was getting dark and the inside seemed crowded with shipping.</p>
          <p>Tonight the sight is one of a lifetime. I wish I could describe it properly. The lights of Colombo, the revolving light high up on the lighthouse and those on the numerous ships, including three or four cruisers, motor boats and steam launches buzzing about make things look like fairyland. We are indeed having a great experience but I would like to be able to have those near and dear to me to share it. Now that we have prisoners of war on board we realize that this is not a pleasure trip but that there may be something very serious at the end of it.</p>
          <p>Tuesday, Nov. 17th. Our first near view of Colombo this morning was great. Inside the breakwater was crowded with shipping and flags of all nations were showing, swarms of native baots were moving about and the Singalese (now called Sri-Lankans) were dressed in loose robes of the gayest of colours. On shore there appeared many large buildings and numerous small ones, nearly all red-roofed, and forests of coco-nut palms in the background.</p>
          <p>There was plenty to interest us all day [we were not allowed ashore]. First thing two or three niggers came aboard with papers and post-cards, others in boats were all round the “Omrah”, trying to sell cigars, cigarettes, coco-nuts, bananas, etc.. One grey headed old chap wanted four shillings a bunch for bananas and sixpence each for coconuts but he got a hot reception and was glad to clear off. Some great diving was done by the niggers after silver coins, one chap, for a shilling, dived off the boat deck, a distance of about 40 feet. All day long the water was crowded with boats and once a steam tug passed us towing 21 water barges. There seem to be many German boats detained here, supposed to be 17. A Japanese four-funnelled cruiser is just near us and have their national flag flying. It must be their washing day for they have about 16 lines of washing hanging out, stretching from the end of the boat to a cross-piece high up on the mast. There is an old type of Russian cruiser here with five funnels, just near the Japanese and a little further on is the good old H.M.A.S. Sydney. We learned today that the fittings off the Emden were to be taken to Australia to adorn the Federal Capital.</p>
          <p>All day long we have been taking in water and about 5 p.m. the anchor was heaved up and we passed slowly out. Our last view of Colombo was one of the prettiest I have ever seen and I will long remember it. The sun was very low and the light soft and yellowish and the effect was lovely. It is beyond my power to describe it. We stopped outside the breakwater till 8 p.m. before continuing our voyage and the numerous lights of Colombo and of the shipping looked lovely. Three very brilliant searchlights were playing and showed up everything within range as bright as day. Moving pictures were shown tonight for the first time but were not very clear. The German prisoners are being kept very quiet, the officers are not allowed to speak to their men. One of the German prisoners told some of the chaps that are guarding them that we will all be sent to hell long before we reach England. If that happens thank goodness they will go with us.</p>
          <p>Wednesday, 18th. We are travelling at about 12 knots. The sea is very calm and smooth, we have had no rough weather at all. One chap here said he believes the Bay of Biscay will stop rolling as soon as we get there. We could see land this morning on the starboard side, the only sight of India we are likely to get. All the New Zealand boats have gone on ahead of us and only nine other troopships are with us - two lines of five each and a cruiser in front.</p>
          <p>Today was pay day, we only get ten shillings a fortnight, not nearly enough to keep us going. The German prisoners seem to be starting their tricks already. This morning one fat German officer asked the sentry to take a towel to one of the other prisoners. It was nicely folded up and the sentry took it to the captain of the guard who shook it out and a note dropped from it. We have not heard what the contents of the note are but the prisoners are watched more closely. The German officers were offered parole when they came on board but refused.</p>
          <p>Monday, Nov. 23rd. Since getting up this morning we have been in sight of land, Sokotra Island, near the bay of Aden. Before you get this letter we will be in England if all goes well. We expect to get to Aden Tuesday night, 24th Nov., three months since we left Gympie</p>





        </section>
        <label for="Dec_27_1914">December 27th, 1914</label>
        <input type="checkbox" name="Mar_15_1916" id="Dec_27_1914">


        <section>
          <h3>Mena Camp</h3>
          <p class="right_align">December 27th. 1914.</p>
          <p>It has not seemed a bit like Xmas here and I have missed the usual good times very much although we are all fairly happy here. Our Coy. were on guard all day Xmas Eve and till 7 o’clock Xmas morning. It was just my luck to be on duty from 11 p.m. to 3 a.m. so I saw Xmas day in. I was walking about near the cook’s galley where our cooks were busy making the plum duff and as there were no officers about I had a good time, although I would rather have been in bed. The puddings [5 large ones] were on at 2 a.m. then we had tea and toast - that was my Xmas breakfast. I was relieved at 3 a.m. and had two hours sleep out in the open near the guard tent, there was no room inside for it was full of prisoners.</p>
          <p>Xmas day was a holiday and church parade was held at 9 a.m., after that leave was granted to about 10% of each Coy.. I and several others in our tent had applied for leave but did not get it, so we took it and went out the back way near the pyramids where there was no guard to stop us. There were crowds of soldiers going to town and every tram, cab and motor car was crowded. Each tram had two trailers behind and only one piastre [two and a half pence] (2 cents) is charged to go the whole distance, about 9 miles. The chaps were not satisfied with filling the trams inside but climbed up on the top too. The conductors tried to get them down but there was no hope in the world, so went into town with about twenty on top of each car, who sang all the way in and threw coins to the nigger kids. It was quite an exciting trip and caused much amusement among the people. Everywhere in the city cafes are springing up with English names such as “The Australian Bar”, “The Soldiers Home”, “Sydney Club”, “Soldiers Club”, etc.. All over the place you will see signs saying: “English spoken” and in many of these shops it would take you all your time to make them understand what you want. All the shopkeepers are up to all sorts of dodges to draw the soldiers and the hawkers in the streets pester the life out of us. Most of them know a word or two of English and we are learning a word or two of Arabic and Egyptian. Cairo is indeed a wonderful city and someday we intend to get a guide to show us all round the historical places. Of course we wander about in all sorts of places but it is a great drawback not knowing the language. If we ask anyone anything they generally want to be paid for it. Boot-blacks swarm about everywhere and we get no peace if we have dirty boots, they clean them for half a piastre. We have forgotten all about English money and only talk in piastres now.</p>
          <p>Well, dear Dot, I am rambling along with this letter somehow but to tell you the truth I hardly know what I am writing about for there are fouteeen of us in the tent and the other twelve are by no means quiet. I am trying to write by a flickering candlelight, with a writing pad on my knee. I have tried to quieten the crowd with all sorts of threats but it is no good, perhaps I ought to climb up the largest pyramid where, no doubt, I would get a little peace. A Xmas box arrived for me on Xmas day in the form of a letter from Mother dated Oct. 24th and addressed to Albany. It was very welcome and so was another one which arrived the next day – also from Mum. This letter has got to be postponed I am sorry to say for our supper has arrived in the shape of oranges and I must join in and be sociable, so they say.</p>
          <p>Jan. 1st. 1915. Well I knew if I did not keep going with this letter that I would not be able to finish it for some time. We are much too busy altogether and have little time for writing – even now I do not know how long I will be able to write. I am writing by candlelight in our mess-room, four of which have been erected for the 9th. Battalion. They are fairly large, built of wood and each one will seat two Companies, about 200 men. This Xmas has been rather a poor one – we have had no holidays except Xmas Day after church parade. On Boxing Day we were marched out as usual and drilled – but had the afternoon off and another chap and I went to town again. In our wanderings we came across an English shop and bought a paper called the “Sphinx” and posted to Dad. We came back to camp by motor car – by jove they do travel fast and the roads are lovely and smooth. There is an avenue about 4 or 5 miles (about 7 to 9 km.) long from Geyser (Giza?) to the Pyramids and trees meet overhead nearly all the way – the road itself being ashphalt.</p>
          <p>Some of our fellows are a bit wild and have been playing up a bit in town and letters of complaint have been written to the Camp Commandant, so the other day the Brigadier paraded the whole of the 3rd Brigade, over 4,000 men, and made a fine speech. He has a great voice and speaking from the top of a sand-hill was heard by everyone quite distinctly. He spoke about the honour of the Empire and of Australia and asked the men to be careful and to behave like soldiers and try and get fit to go to the front. He said that as soon as he could report us fit and ready to the General we would be sent to the front. All men who turn out blackguards are to be sent back to Australia. Some of the men here are that bad that they have to be sent to the Citadel prison [military one] where they get a hot time. On Wednesday last 18 prisoners had to be sent in and an escort of 13 was picked to guard them. I, with three other of the Gympie lads, was part of the escort and we were told that the prisoners were to be handed over at the Citadel even if they were in pieces. Ammunition was served out to us, so we loaded our rifles, fixed bayonets and marched them off. They made no attempt to escape and after a weary march of about 10 miles (about 17 km.) we lobbed them in safely. We all marched to a café then and had a good tea. It cost us 108 piastres [about 22 shillings] ($2.20) and we had our moneys worth. Of course, having rifles and cartridges we could not stay in town so came back to camp by tram at the expense of the regiment. We were away from 12 noon till 9 p.m. and the cooks had a dixie ot tea waiting for us so we had another tea.</p>
          <p>Yesterday afternoon Sir George Reid inspected us and made a speech, after which there was a “march past” of the whole 3rd Brigade and Army Service Corps. It took nearly ¾ of an hour to march past and a massed band played all the time, there were 20 kettle drums, 1 large drum and 30 or more other instruments. A change has been made in the 9th Battalion and all other Battalions too – instead of there being 8 Comps. as before, there are now only four, our Coy. [F] and H Coy have been joined together and the whole is called D Coy.. It is what is called Platoon formation – there are 4 Platoons in each Coy.. All the Gympie lads are in No. 13 Platoon under George Thomas. Capt. Jackson will be over D. Coy. of 4 platoons, Nos. 13,14,15,16, which will be a rise for him as only 4 Captains are required now where there were 8 before. He will have a horse to ride and have 4 Lieuts and about 200 men under him.</p>
          <p>My address will now be 13th Platoon, D.Coy., 9th Infantry, 3rd Brigade, 1st Australian Division, Mena Camp, Cairo, Egypt. although other letters with the old address will find me. It would be advisable to add my regimental number, 692, before my name.</p>
          <p>Well, dear Dot, I think I will have to end this letter now, with the hope that I will be able to write again soon. We do not expect to leave here before the end of Feb., perhaps not then. There are many places I would like to visit in Cairo and will tell you about them another time. One old place I visited was some Sultan’s Mosque, over 1,000 years old – a grand stone building. There was a marble tomb there, a stand to hold the Koran and the Sultan’s throne. The guide told us that anyone who sat in the chair and wished would be sure to get it, so I tried it and had a wish concerning all of you at home. I have a lot of PC’s and will send them on from time to time.</p>
          <p>Well, dear Dot, I think I will have to end this letter now, with the hope that I will be able to write again soon. We do not expect to leave here before the end of Feb., perhaps not then. There are many places I would like to visit in Cairo and will tell you about them another time. One old place I visited was some Sultan’s Mosque, over 1,000 years old – a grand stone building. There was a marble tomb there, a stand to hold the Koran and the Sultan’s throne. The guide told us that anyone who sat in the chair and wished would be sure to get it, so I tried it and had a wish concerning all of you at home. I have a lot of PC’s and will send them on from time to time.</p>
          <p>P.S. The general opinion here is that the 9th Battalion is ahead of the other Battalions and more fit to go to the front. F Coy. won the prize of the whole 9th Batt. for having the cleanest lines since being in camp.</p>
        </section>

        <h3>1916</h3>

        <label for="Mar_15_1916">March 15th, 1916</label>
        <input type="checkbox" name="Mar_15_1916" id="Mar_15_1916">
        
        <section>
          <h3>Serapeum, Suez Canal</h3>
          <p class="right_align">15th March 1916.</p>
          <p>Dear Alice,</p>
          <p>A letter from you has just come to hand dated Jan. 16th. , It has been a considerable time on the way but I was jolly glad to get it all the same. One that I received about a week ago from Mother was dated Feb 11th so you see the mails are very irregular. </p>
          <p>Since writing to Herb we have not done much or met with any exciting adventures and are still in the same place on the eastern bank of the Suez Canal. The most important event has been the brigading of the machine gun sections of the 3rd Brigade, which was completed on the 13th inst.. The 9th, 10th, 11th and 12th M. G. S’s are now combined and now form the No. 3 Machine Gun Company – we are separated altogether from the Battalions but are still attached to the famous 3rd Brigade. We have a separate camp of our own now laid out in this style:</p>
          <img src="/media/tents_layout.jpg" alt="A sketch of the layout of the tents, mess, orderly room, canteen, cookhouse, railway, road, canal, etc..">
          <p>Sunday, March 19th. 1916.</p>
          <p>Dear Sister, This letter has been delayed several days through want of time and also want of news. Now I have a little time to myself and also a little news so I will endeavour to finish it off. The most important item is the surprise we of the 3rd Brigade received this morning at church parade when His Royal Highness Edward, Prince of Wales put in his appearance accompanied by General Birdwood and a dozen other “Big Hits”. We were formed up as the three sides of a square so:-</p>
          <img src="/media/diagram_positions.jpg" alt="A diagram of the positions of the Prince and staff, the parson, the 3rd M.G.Co., 9th, 10th, 11th and 12th Battalions, making a square.">
          <p>and I was in a good position to view the Prince. He is very much like the photos you often see and I recognized him at once. He was present throughout the service, the sermon of which was preached by the Rev. Lundy while some other Rev. Pot (i.e. man, name unknown) conducted the filling that usually accompanies the C of E services. After church parade General Birdwood [beloved by all the Anzacs] made a fine speech, opening by introducing the Prince of Wales whom, he said, was very pleased to have the opportunity of seeing the Australians and wished them every success and a safe return to their homes. Gen. Birdwood was very emotional during his speech in his praise of the Australians on their conduct at Gallipoli and he said he considered it an honour to command such fine troops, but he rubbed it in just a little bit about our slackness in discipline although he said we were improving. The Prince looked very boyish and slim, he has a lovely complexion and looks younger than he really is. After Gen, Birdwood’s speech our Brigadier called for three cheers for H.R.H. and they were given with a will while the Prince stood at the salute. Then came a “march past” of the whole brigade, the Prince of Wales taking the salute at a point where an Australian flag had been hoisted. And so the famous 3rd Brigade was honoured by being the first to be reviewed by a Royal Personage. </p>
          <p>General Birdwood also mentioned in his speech that very shortly we would be going to France and he hoped that we would uphold the honour we had already won.  It will be alright to get there and perhaps we may yet fight against the Germans – but I do not think Our fellows will ever be as good as the first 20,000 that left Australia. The other day we had to undergo another innoculation [the 5th.] this time for Para-Typhoid and for 24 hours it was very severe, first making us very sleepy then giving us pains all over the body and bad head-aches.  We are now being fitted out with all new equipment,  yesterday 16 new Vickers Maxim guns arrived and all our old guns have been handed in – we will get new rifles also for Mark VII ammunition and new clothing, some of which has already been issued.</p>
          <p>Dear Al, I have proved that I am very light on boots for I have not had a new pair since I left Enoggera where two pairs were issued to each man.  My first pair are worn out but the second are good for months yet – not bad for 19 months wear, with miles and miles of marching in Egypt, Lemnos, Anzac, Malta and on this rotten desert.  The sandstorms here are awful at times, it is impossible to face the wind and sand.  I never thought when reading about them in the school books that I would ever experience them myself.</p>
          <p>We have heard that all mails to Australia are to be stopped for 6 weeks.  I hope it is not true and that this will reach you safely without too much delay.  How is the dear Mother keeping, that is the question always first with me and I hope she is well and also all of you.   I had a good yarn with Mag in my dreams last night, she was just the same old Peg.  I may not be able to write a decent latter for some time so do not be alarmed if you get none, but I will drop a line as often as possible.</p>
          <p>Best of love dear Al to you all,</p>
          <p class="right_align">Your loving brother,</p>
          <p class="right_align">Ray.</p>
          <p>P.S.  Remember me to all friends.</p>


        </section>

        <label for="Feb_4_1917">February 4th, 1917</label>
        <input type="checkbox" name="Feb_4_1917" id="Feb_4_1917">

        <section>
          <h3>France, Fricourt Farm.</h3>
          <p class="right_align">4th February 1917</p>
          <p>My Dear Mother,</p>
          <p>We have just been rudely informed that an Australian mail closes at 11 a.m. this morning, it is now 10.30 a.m. so I am trying to get away a few lines to you, for I do not like a mail to go by.  But there is so little news to tell and everything is ice, snow and frost-bound so that one cannot settle down to do a thing in comfort.  Yesterday we moved from the tents we were in at Millancourt, marched through Albert and now are in warmer quarters at Fricourt – well closed up huts – and we have a fire going all the time, but have to pinch our wood.  There seems to be no chance of a break in the weather – it continues to freeze, I think the temperature is nearly down to Zero.  The last mail from Aus was late in getting here, two days ago I got your long and interesting letter of Dec. 1st and also Doris’s Dec. 17th.  She is a nut of a kid.  Hope she writes again.  This is a slap-up letter, Mum but the Corporal waits to collect the mail.  I am in good health.  Hope all at home are the same. Best of love to everyone from,</p>
          <p>Your loving son,</p>
          <p class="right_align">Ray.</p>
        </section>

      </article>


    </main>

    <footer>
      <div>&copy;<script>
          document.write(new Date().getFullYear());
        </script> Camilo Jaramillo Diaz, s3820251. Last modified <?= date("Y F d  H:i", filemtime($_SERVER['SCRIPT_FILENAME'])); ?>.</div>
      <div>Disclaimer: This website is not a real website and is being developed as part of a School of Science Web Programming course at RMIT University in Melbourne, Australia.</div>
      <div><button id='toggleWireframeCSS' onclick='toggleWireframe()'>Toggle Wireframe CSS</button></div>
    </footer>

  </body>
</php>